name: Build executables

on:
  push:
    tags:
      - "b*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pyinstaller

      - run: |
          pyinstaller \
            --onefile \
            --name stardewfishing \
            --add-data "assets:assets" \
            stardewfishing.py

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/stardewfishing

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pyinstaller

      - run: |
          pyinstaller ^
            --onefile ^
            --windowed ^
            --name stardewfishing ^
            --add-data "assets;assets" ^
            stardewfishing.py

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/stardewfishing.exe